"""empty message

Revision ID: 1441fb4f93e
Revises: 52e6788ad0e
Create Date: 2015-11-28 22:44:08.483220

"""

# revision identifiers, used by Alembic.
revision = '1441fb4f93e'
down_revision = '52e6788ad0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
