"""empty message

Revision ID: 36365173d3bd
Revises: 3426548f3767
Create Date: 2015-07-20 16:16:48.292303

"""

# revision identifiers, used by Alembic.
revision = '36365173d3bd'
down_revision = '3426548f3767'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('update_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'update_id')
    ### end Alembic commands ###
