"""empty message

Revision ID: 3b32109b2944
Revises: 1441fb4f93e
Create Date: 2015-11-28 22:57:49.551787

"""

# revision identifiers, used by Alembic.
revision = '3b32109b2944'
down_revision = '1441fb4f93e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_favorite',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'channel_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_favorite')
    ### end Alembic commands ###
