"""empty message

Revision ID: 52e6788ad0e
Revises: 1ffff3fad934
Create Date: 2015-09-12 19:28:42.487702

"""

# revision identifiers, used by Alembic.
revision = '52e6788ad0e'
down_revision = '36365173d3bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('update', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'update')
    ### end Alembic commands ###
