"""empty message

Revision ID: 59c60d65c1b6
Revises: 3b32109b2944
Create Date: 2016-03-23 15:01:54.088304

"""

# revision identifiers, used by Alembic.
revision = '59c60d65c1b6'
down_revision = '3b32109b2944'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'active')
    ### end Alembic commands ###
